name: Convert DB to JSON

on:
  schedule:
    - cron: '0 15 * * *'  # 매일 KST 00:00에 실행
  workflow_dispatch:  # 수동 실행 옵션

permissions:
  contents:
    write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run conversion script
      run: python $GITHUB_WORKSPACE/src/convert_db_to_json.py
    - name: Commit and push if changed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add json/bookmarks.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update bookmarks.json" && git push)
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
